# You can find your Meetup URL name in any of the meetup event paths
# EX: http://www.meetup.com/Code-for-San-Jose
meetup_url_name: 'Code-for-San-Jose'

# The amount of hours waited per time that Meetup events are fetched
meetup_poll_time: 1